modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
updateJSONURL="https://raw.githubusercontent.com/MinecraftModDevelopmentMods/ironagefurniture/master/update.json"
issueTrackerURL="https://github.com/MinecraftModDevelopmentMods/ironagefurniture/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ironagefurniture"
logoFile=""
credits="SkyBlade1978"
authors="SkyBlade1978"

[[mods]]
modId="ironagefurniture"
version="${file.jarVersion}"
displayName="Iron Age Furniture"
description='''
Furniture from the Iron Age!
'''

[[dependencies.ironagefurniture]]
   modId="forge"
   mandatory=true
   versionRange="[34,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.ironagefurniture]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.1]"
   ordering="NONE"
   side="BOTH"